### ISSUE TITLE
VyTrack repository has been updated. 

### ISSUE THREAD

**Issue by TamerlanHuseynov** [TamerlanHuseynov/vytrackAutomation#1]
Try to checkout to master and click update. Then checkout to your branch and then right-click on master in order to choose "merge master into your branch". After doing it check if you have new updated files in your branch.
![ScreenShot_20220304173113](https://user-images.githubusercontent.com/45001026/156850756-7856adac-84ab-4d5e-bcaf-261d1c76d4e0.jpeg)

**Comment by vupham129** [comment]
I read and merged to my branch. Thank you.

**Comment by MohammedAlshalchi** [comment]
I did 
thanks
