### ISSUE TITLE
VyTrack repository has been updated. 

### ISSUE THREAD

**Issue by TamerlanHuseynov** [TamerlanHuseynov/vytrackAutomation#2]
I have added TestBase class which needs to be extended in your own classes in order to get inheritance for
@BeforeMethod and @AfterMethod procedures. These Methods already include driver setup and close diver.
Because of this extension, we are gonna use getDriver() in order to call driver (before we were creating
Web Driver object and using it by calling 'driver.' but now we are gonna use getDriver(), this method is
located under Utilities. Driver class which already creates driver object and does
everything(even calls an 'env' which opens the env that we need to test)there every time when we call it.
P.S Don't forget to use VyTrack_Login class for quick logging into the accounts. Because TestBase class only includes
Driver object creation, browser open steps. It only goes to the site that we have been provided. So, calling VyTrack_Login is mandatory. 

- ![ScreenShot_20220305230426](https://user-images.githubusercontent.com/45001026/156909274-1413166d-66f2-47f3-807a-3a35af70413c.jpeg)

Enjoy!

**Comment by olesiasokol** [comment]
Great and helpful work, Tamerlan! Thank you!

**Comment by vupham129** [comment]
Thank you for your effort
